# Following are chance percent settings for each mob and variants of mobs.
# 0.001 = 1/10 of 1 percent, 0.01 = 1 percent, 1.00 = 100 percent
chance_percent:
  allay: 0.02
  armadillo: 0.01
  axolotl:
    lucy: 0.01
    wild: 0.01
    gold: 0.01
    cyan: 0.01
    blue: 0.01
  bat: 0.01
  bee: 0.005
  blaze: 0.002
  bogged: 0.002
  breeze: 0.002
  camel: 0.0025
  cat:
    all_black: 0.01
    black: 0.01
    british_shorthair: 0.01
    calico: 0.01
    jellie: 0.01
    persian: 0.01
    ragdoll: 0.01
    red: 0.01
    siamese: 0.01
    tabby: 0.01
    white: 0.01
  cave_spider: 0.002
  chicken: 0.00125
  cod: 0.01
  cow: 0.002
  creeper: 0.004
  creeper_charged: 0.1
  dolphin: 0.025
  donkey: 0.006667
  drowned: 0.0025
  elder_guardian: 0.125
  ender_dragon: 1.00
  enderman: 0.0025
  endermite: 0.01
  evoker: 0.05
  fox:
    red: 0.01
    snow: 0.01
  frog:
    temperate: 0.004
    cold: 0.004
    warm: 0.004
  ghast: 0.01
  giant: 0.025
  glow_squid: 0.005
  goat: 0.004
  guardian: 0.015625
  hoglin: 0.005
  horse:
    black: 0.01
    brown: 0.01
    chestnut: 0.01
    creamy: 0.01
    dark_brown: 0.01
    gray: 0.01
    white: 0.01
  husk: 0.002
  illusioner: 0.25
  iron_golem: 0.01
  llama:
    brown: 0.004
    creamy: 0.004
    gray: 0.004
    white: 0.004
  magma_cube: 0.002
  mule: 0.006667
  mushroom_cow:
    red: 0.01
    brown: 0.01
  ocelot: 0.025
  panda:
    aggressive: 0.01
    brown: 0.01
    lazy: 0.01
    normal: 0.01
    playful: 0.01
    weak: 0.01
    worried: 0.01
  parrot:
    blue: 0.015625
    cyan: 0.015625
    gray: 0.015625
    green: 0.015625
    red: 0.015625
  phantom: 0.01
  pig: 0.002
  piglin: 0.002
  piglin_brute: 0.025
  pig_zombie: 0.002
  pillager: 0.0066667
  polar_bear: 0.01
  pufferfish: 0.01
  rabbit:
    black: 0.0075
    black_and_white: 0.0075
    brown: 0.0075
    gold: 0.0075
    salt_and_pepper: 0.0075
    the_killer_bunny: 1.00
    toast: 0.0075
    white: 0.0075
  ravager: 0.1
  salmon: 0.01
  sheep:
    black: 0.002
    blue: 0.002
    brown: 0.002
    cyan: 0.002
    gray: 0.002
    green: 0.002
    light_blue: 0.002
    light_gray: 0.002
    lime: 0.002
    magenta: 0.002
    orange: 0.002
    pink: 0.002
    purple: 0.002
    red: 0.002
    white: 0.002
    yellow: 0.002
  shulker: 0.025
  silverfish: 0.015
  skeleton: 0.001
  skeleton_horse: 0.25
  slime: 0.002
  sniffer: 0.02
  snowman: 0.01
  spider: 0.002
  squid: 0.01
  stray: 0.002
  strider: 0.015625
  tadpole: 0.01
  trader_llama:
    brown: 0.05
    creamy: 0.05
    gray: 0.05
    white: 0.05
  # ########################################
  tropical_fish: 0.01
  turtle: 0.005
  vex: 0.025
  villager: 0.005
  vindicator: 0.025
  wandering_trader: 0.1
  warden: 0.25
  witch: 0.01
  wither: 0.25
  wither_skeleton: 0.025
  wolf:
    pale: 0.01
    spotted: 0.01
    snowy: 0.01
    black: 0.01
    ashen: 0.01
    rusty: 0.01
    woods: 0.01
    chestnut: 0.01
    striped: 0.01
  zoglin: 0.01
  zombie: 0.001
  zombie_horse: 1.00
  zombie_pigman: 0.0025
  zombified_piglin: 0.0025
  zombie_villager: 0.001